name: field_report
description: "Field documentation done easy"
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  image_picker: 
  image: ^4.0.5 
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  camera: ^0.11.0+2  
  cupertino_icons: ^1.0.8
  geolocator: ^9.0.2
  geocoding: ^2.0.4
  intl: ^0.19.0
  provider: ^6.0.1
  pdf: ^3.3.0
  printing: ^5.6.0
  share_plus: ^4.0.10
  advance_pdf_viewer: ^2.0.0
  http: ^0.13.3
  flutter_dotenv: ^5.1.0
  syncfusion_flutter_pdf: ^21.2.4
  feedback: ^3.1.0
  connectivity_plus: ^6.1.0
  sqflite: ^2.0.0+3
  path: ^1.8.0
  file_picker: ^8.1.3
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.4

 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ATLogo.png
    - assets/GRC.png
    - assets/NonVisitedATC.pdf
    - assets/VisitedATC.pdf
    - assets/psATLogo.png
    - assets/PDFLOGO.png
